export const statusbarFacts = {
  tokens: [
    'Tokens são pedaços de palavras. Exemplo: [Olá] [!] [mundo] [!] = 4 tokens',
    'Tokens são como blocos de LEGO: cada palavra pode virar vários tokens! 🧱',
    'Quanto mais tokens, mais caro para a IA. Use com sabedoria! 💸',
    'Sabia que “ChatGPT” é 2 tokens? [Chat] [GPT]',
    'Em inglês, palavras curtas costumam ser 1 token. Em português, pode ser mais!',
    'Token não é moeda, mas vale ouro para a IA! 🪙',
    'Se cada token fosse um grão de arroz, daria pra fazer um risoto de IA!',
    'Token demais, tradução a menos! Use com moderação.',
    'A IA conta tokens igual criança conta bala: um por um!',
    'Token é tipo sílaba, mas a IA inventa as regras!',
  ],
  elapsed: [
    'Processamento: {ms} ms. Um piscar de olhos dura cerca de 300 ms! 👀',
    'Já pensou? Em {ms} ms a IA traduziu tudo!',
    'Mais rápido que preparar um café! ☕',
    'Tempo de tradução menor que o tempo de digitar “Olá”! ⌨️',
    'Se fosse uma tartaruga, levaria horas... 🐢',
    'A IA não perde tempo: só ganha tokens!',
    'Se fosse um humano, ainda estaria lendo o texto!',
    'Tempo suficiente pra dar um like na página! 👍',
    'A IA não pisca, mas traduz em milissegundos!',
    'Se fosse um elevador, nem teria chegado no 1º andar ainda!',
  ],
  speed: [
    'Se fosse uma tartaruga, seria mais devagar. 🐢',
    'Velocidade de tokens digna de um foguete! 🚀',
    'Quanto maior, mais rápida a tradução.',
    'A IA não dorme: traduz tokens a toda hora! 😴',
    'Já pensou traduzir isso manualmente? 😅',
    'Mais rápido que notícia ruim!',
    'Se fosse um carro, já teria tomado multa de velocidade!',
    'A IA acelera mais que café forte!',
    'Traduzindo tokens no modo turbo!',
    'Se fosse um atleta, ganhava medalha de ouro!',
  ],
  payload: [
    'Daria pra enviar isso por pombo-correio? Talvez não... 🕊️',
    'Payload é o tamanho do pacote enviado para a IA.',
    'Quanto maior o payload, mais tokens e mais custo.',
    'Payload grande = mais tempo de processamento.',
    'Divida textos grandes para economizar tokens!',
    'Se fosse uma carta, o carteiro ia reclamar!',
    'Payload pequeno, IA feliz!',
    'Se coubesse num tweet, seria fácil!',
    'Quanto menor o payload, mais rápido chega!',
    'Payload gigante, paciência de gigante!',
  ],
  charCount: [
    'Já pensou em escrever um livro? Esse texto já é um capítulo! 📖',
    'Caracteres contam tudo: letras, espaços, pontuação...',
    'Um tweet tem até 280 caracteres. Quantos tweets tem seu texto?',
    'Quanto mais caracteres, mais tokens!',
    'A IA adora textos longos, mas seu bolso nem tanto! 💸',
    'Se cada caractere fosse um passo, você já teria dado a volta no quarteirão!',
    'Texto curto, tradução rápida!',
    'Se fosse um SMS, já teria cobrado extra!',
    'Caracteres são como formigas: quando você vê, já tem um monte!',
    'Se fosse um código, já dava pra fazer um Hello World!',
  ],
  cost: [
    'Com esse valor, quase dá pra comprar um café... ☕',
    'O custo depende do modelo e da separação entre tokens de entrada e saída.',
    'Quanto menor o custo, mais traduções por dólar!',
    'Dá pra traduzir muita coisa com 1 dólar, hein? 💵',
    'Fique de olho: textos grandes podem custar mais!',
    'Se fosse promoção, seria Black Friday de tokens!',
    'Custo baixo, alegria alta!',
    'Se fosse um lanche, seria só a batata!',
    'Com esse preço, até a IA fica feliz!',
    'Se fosse um ingresso, seria meia-entrada!',
  ],
  reqs: [
    'Dá pra traduzir muita coisa com 1 dólar, hein? 💵',
    'Com $1 você faz milhares de traduções pequenas!',
    'Economize tokens para traduzir mais vezes.',
    'Requisições grandes gastam mais rápido seu saldo.',
    'Aproveite cada requisição: IA não é de graça!',
    'Se cada requisição fosse um pão, dava pra fazer uma padaria!',
    'Requisição pequena, alegria garantida!',
    'Se fosse um pedido, a IA seria garçom!',
    'Com tantas requisições, a IA já te conhece pelo nome!',
    'Se fosse um delivery, já teria chegado!',
  ],
  model: [
    'Esse modelo é mais inteligente que muito humano! 🤖',
    'Modelos diferentes, custos diferentes. Fique atento!',
    'Modelos pequenos como gpt-4o-mini costumam ser bem econômicos para tradução.',
    'A cada ano, modelos ficam mais poderosos!',
    'Você está usando IA de última geração!',
    'Se fosse um robô, já teria passado no ENEM!',
    'Modelo novo, curiosidade renovada!',
    'Se fosse um super-herói, seria o GPTman!',
    'A IA não dorme, só evolui!',
    'Se fosse um professor, já teria dado aula pra muita gente!',
  ],
};
